const DummyData = [
  {
    id: 1,
    rack_name: "RACK1",
  },
  { id: 2, rack_name: "RACK2" },
  { id: 3, rack_name: "RACK3" },
  { id: 4, rack_name: "RACK1" },
  { id: 5, rack_name: "RACK1" },
  { id: 6, rack_name: "RACK1" },
  { id: 7, rack_name: "RACK1" },
  { id: 8, rack_name: "RACK1" },
  { id: 9, rack_name: "RACK1" },
  { id: 10, rack_name: "RACK1" },
  { id: 11, rack_name: "RACK1" },
  { id: 12, rack_name: "RACK1" },
  { id: 13, rack_name: "RACK1" },
  { id: 14, rack_name: "RACK1" },
  { id: 15, rack_name: "RACK1" },
  { id: 16, rack_name: "RACK1" },
  { id: 17, rack_name: "RACK1" },
  { id: 18, rack_name: "RACK1" },
  { id: 19, rack_name: "RACK1" },
  { id: 20, rack_name: "RACK1" },
  { id: 21, rack_name: "RACK1" },
  { id: 22, rack_name: "RACK1" },
  { id: 23, rack_name: "RACK1" },
  { id: 24, rack_name: "RACK1" },
  { id: 25, rack_name: "RACK1" },
  { id: 26, rack_name: "RACK1" },
  { id: 27, rack_name: "RACK1" },
  { id: 28, rack_name: "RACK1" },
  { id: 29, rack_name: "RACK1" },
  { id: 30, rack_name: "RACK1" },
];
export default DummyData;
